export default [
	{
		id: '0',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манга',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga.png',
		chapters: [
			{
				id: 0,
				free: true,
				number: 37,
				data: '10 Февраля 2023',
			},
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
	{
		id: '1',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манга',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga_1.png',
		chapters: [
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
	{
		id: '2',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манга',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga.png',
		chapters: [
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
	{
		id: '3',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манга',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga_1.png',
		chapters: [
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
	{
		id: '4',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манхва',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga.png',
		chapters: [
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
	{
		id: '5',
		titleRu: 'Охотник в другом мире',
		titleEng: 'Hunter in another world',
		titleKorean: '헌터 인또 다른 세계 ',
		views: 200,
		bookmarks: 1200,
		year: 2002,
		description:
			'В современном Хоккайдо появился бурый медведь возле начальной школы, поэтому член местной ассоциации охотников отправляется его устранить. Однако он был убит медведем и просыпается...',
		type: 'манга',
		status: 'продолжается',
		genres: [
			{ title: 'Комедия', id: 0 },
			{ title: 'Драма', id: 1 },
			{ title: 'Путин', id: 2 },
			{ title: 'Драма', id: 3 },
			{ title: 'Путин', id: 4 },
		],
		bookJacket: '/images/manga_1.png',
		chapters: [
			{
				id: 1,
				free: true,
				number: 38,
				time: '4 часа назад',
				data: '10 Февраля 2023',
			},
			{
				id: 2,
				free: true,
				number: 39,
				time: '2 дня назад',
				data: '10 Февраля 2023',
			},
			{
				id: 3,
				free: false,
				number: 40,
				time: '3 дня назад',
				data: '10 Февраля 2023',
			},
		],
	},
]
